### ISSUE TITLE
Add objectType property to our model used in oneOf or anyOf 

### ISSUE THREAD

**Issue by patrice-conil** [camaraproject/WorkingGroups#168]
As mentionned in Openapi doc [here](https://spec.openapis.org/oas/v3.1.0#discriminator-object) usage of discriminator may simplify serialization/deserialization process.

If we added an objectType property to our object involved in oneOf or anyOf sections we could add a section like this:
```
...
Object1:
  type: object
  properties:
    objectType: string
    ...
  required:
    - objectType
    - ...

Object2:
  type: object
  properties:
    objectType: string
    ...
  required:
    - objectType
    - ...

CompositeObject:
    type: object
    oneOf:
        - $ref: Object1
        - $ref: Object2
    discriminator:
        propertyName: objectType
```
to help serialization/deserialization process.
What do you think about this proposal?
