### ISSUE TITLE
E/// proposal to use GPSI as UE identifier

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#4]

**Comment by T-sm** [comment]
Ericsson has uploaded their proposal to the WG repo: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Deliverables/UE%20identifiers.pptx

**Comment by jordonezlucena** [comment]
Agree with the solution proposed by Ericsson. 
One question on slide 6, step 1. What happens if the UE IP address is private? Would it work?

**Comment by shilpa-padgaonkar** [comment]
Agree with solution proposed by E/// to include GPSI-External_Id as a valid option for UE identification.
For the current QoD APIs, changes will be made after NEF AsSessionWithQoS API includes this option or when a separate relevant NEF API offers the needed capability to keep the complexity of service api implementation to the minimum and ensure validations.

**Comment by Kevsy** [comment]
Agree that MSISDN should not be used as per privacy and regulations. 

Agree that GPSI-Extrenal_Id is a good 3GPP compliant

> what this policy says that the operator is not allowed to sell QoS per gaming app
@jordonezlucena I *think* this may be possible if it is the end user that has requested and provided explicit consent to the upgraded QoS for a particuar app. But that needs to be checked on a per market basis by the regulatory teams.

**Comment by eric-murray** [comment]
- Vodafone support the Ericsson proposal to use GPSI as a possible identifier for the UE and as an alternative to the UE source IP address & port.
- Either a MSISDN or External Identifier should be able to be specified as the GPSI. MSISDN should NOT be excluded as a possible identifier just because of potential privacy concerns or the possibility that a MSISDN could be transferred to another subscriber.
- Definition should be the same as defined by 3GPP in TS 29.571, i.e.
```
   Gpsi:
      type: string
      pattern: '^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$'
      description: String identifying a Gpsi shall contain either an External Id or an MSISDN. It shall be formatted as follows -External Identifier= "extid-<extid>, where <extid> shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an External Identifier.
```
- Operator issued tokens identifying the UE should also be supported as an alternative to GPSI if the GPSI is unknown or cannot be used for privacy or other reasons, but that should be discussed as a separate issue.
